[bar.main]
position = "bottom"
thickness = 38
background_opacity = 0.93
radius = 18
concave_edge_corners = true
margin_ends = 16
margin_edge = 0
padding = 12
widget_spacing = 6
scale = 1.0
font_scale = 1.0
font_family = "JetBrainsMono Nerd Font"
shadow = true
auto_hide = false
reserve_space = true
capsule = false
start = ["os-logo", "launcher", "workspaces", "taskbar"]
center = ["media"]
end = ["tray", "network", "notifications", "battery", "volume", "brightness", "clock", "control-center", "session"]
