[bar.main]
position = "top"
thickness = 34
background_opacity = 0.93
radius = 0
margin_ends = 0
margin_edge = 0
padding = 8
widget_spacing = 6
scale = 1.0
font_scale = 1.0
font_family = "JetBrainsMono Nerd Font"
shadow = true
auto_hide = false
reserve_space = true
capsule = true
start = ["os-logo", "clock", "active_window"]
center = ["workspaces"]
end = ["media-compact", "tray", "network", "notifications", "battery", "volume", "brightness", "bar-profile", "control-center"]
